version: "3.9"

services:
  db:
    restart: always
    image: postgres:14.6-alpine
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    restart: always
    build: backend
    command:
      bash entrypoint.sh
    volumes:
      - ./backend:/opt/app
      - ./static:/opt/app/static
      - ./media:/opt/app/media
    env_file:
      - .env
    ports:
      - "8081:8080"
    depends_on:
      - db

  nginx:
    restart: always
    image: staticfloat/nginx-certbot
    volumes:
      - ./static:/opt/app/static
      - ./media:/opt/app/media
      - ./nginx_ssl:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
    env_file:
      - .env
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - backend

volumes:
  static:
  media:
  db_data:
  letsencrypt: